# Generated by Django 2.2 on 2019-05-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190501_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
