# Generated by Django 2.2 on 2019-05-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190504_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
