# Generated by Django 2.2 on 2019-05-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
