# Generated by Django 2.2 on 2019-05-13 21:31

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190513_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profileimg/default/default.png', upload_to=account.models.upload_path_handler),
        ),
    ]
