# Generated by Django 2.2 on 2019-05-14 00:14

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190513_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profileimg/default/default.jpg', upload_to=account.models.upload_path_handler),
        ),
    ]
