# Generated by Django 2.2 on 2019-05-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='total_likes',
        ),
    ]
